services:
  backend:
    image: node:19
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "82:9000"
    command: sh -c "
      chmod +x /usr/src/app/startup.sh &&
      /usr/src/app/startup.sh"

  # Frontend Development Setup
  # Uncomment the following block for development (hot-reloading)
  # Run `docker-compose up` and access the React dev server at http://localhost:3000
  # frontend:
  #   image: node:19
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   command: sh -c "
  #       npm install &&
  #       npm start"

  # Frontend Production Setup
  # Uncomment the following block for production (Nginx serving built React files)
  # Build the React app using `npm run build` before running this setup
  frontend:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - "81:80"
