services:
  backend:
    image: node:19
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "82:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/DrD
      - JWT_SECRET=your_jwt_secret_key
    command: sh -c "
      chmod +x /usr/src/app/startup.sh &&
      /usr/src/app/startup.sh"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  frontend:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "81:80"

volumes:
  mongodata:
