name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

    # Step 3: Build backend Docker image
    - name: Build Backend Image
      run: docker build -t "${{ env.DOCKER_HUB_USERNAME }}/backend" ./backend

    # Step 4: Build frontend Docker image
    - name: Build Frontend Image
      run: docker build -t "${{ env.DOCKER_HUB_USERNAME }}/frontend" ./frontend

    # Step 5: Push backend Docker image to Docker Hub
    - name: Push Backend Image
      run: docker push "${{ env.DOCKER_HUB_USERNAME }}/backend"

    # Step 6: Push frontend Docker image to Docker Hub
    - name: Push Frontend Image
      run: docker push "${{ env.DOCKER_HUB_USERNAME }}/frontend"
